### ISSUE TITLE
Theme About page/on-boarding issues

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/philosophy#11]
- There's no notification when first installing Philosophy, in previous version, there was.
- Recommended plugins have nothing to do with Colorlib
- Registration tab shouldn't exist (and all functionality associated with it)
- Privacy tab should be checked if those options are even used.

**Comment by codepixar** [comment]
Hello cristianraiber,
We already work on this issue last PR. Which point are remaining ?

**Comment by cristianraiber** [comment]
Will check this tomorrow morning and report back.

**Comment by cristianraiber** [comment]
@codepixar - made a few small changes, but otherwise, all good.
