### ISSUE TITLE
Encountering an https 500 error upon installing the theme. 

### ISSUE THREAD

**Issue by gssaditya** [ColorlibHQ/philosophy#19]
I got an HTTPs 500 error immediately  after activating the theme.
Could not use the theme at all. I am running WordPress 5.01.

**Comment by cristianraiber** [comment]
@codepixar - please look into this.

**Comment by gssaditya** [comment]
The error is

 Class 'Epsilon_Section_Navigation_Menu' not found in themes/philosophy-dev/inc/class-epsilon-init-dashboard.php on line 172

**Comment by cristianraiber** [comment]
@gssaditya - did you clone from this repo? :) Then you didn't clone properly. ZIP of this theme can be downloaded from here: https://colorlib.com/downloads/philosophy.zip

**Comment by gssaditya** [comment]
Thank You so much.
