### ISSUE TITLE
Can't activate philosophy theme

### ISSUE THREAD

**Issue by themeshef** [ColorlibHQ/philosophy#21]
![image](https://user-images.githubusercontent.com/29626001/55774078-834db880-5ab5-11e9-9b83-1b02dfba47e5.png)

Am I the only one who face this problem with philosophy theme? 
Uncaught Error: Class 'Epsilon_Section_Navigation_Menu' not found.

**Comment by cristianraiber** [comment]
@themeshef - you should never clone directly from GitHub unless you know what you're doing. Philosophy theme bundles git submodules that can only be pulled via Git's CLI.
