### ISSUE TITLE
Tagline isn't displayed

### ISSUE THREAD

**Issue by razvanaldea89** [ColorlibHQ/philosophy#22]

**Comment by codepixar** [comment]
Please give me a screenshot, where Tagline isn't displayed.

**Comment by razvanaldea89** [comment]
Philosophy
![phylosophy](https://user-images.githubusercontent.com/44024114/57833872-b45f8e00-77c3-11e9-9a9c-b3135f53872a.PNG)


Twentyninteen
![twentyninteen](https://user-images.githubusercontent.com/44024114/57833880-b9244200-77c3-11e9-8198-486d781523be.PNG)

**Comment by codepixar** [comment]
Fixed in v1.1.2
