### ISSUE TITLE
Color picker cut off

### ISSUE THREAD

**Issue by razvanaldea89** [ColorlibHQ/philosophy#26]
In some circumstances the color picker is cut off
![philosofy customize invalid values 2](https://user-images.githubusercontent.com/44024114/56218395-92aca300-606d-11e9-9f6f-d7607a18609f.PNG)

**Comment by razvanaldea89** [comment]
The one above isn't the only one where the colorpicker is cut off.

**Comment by cristianraiber** [comment]
@razvanaldea89 this is actually a bug from Epsilon Framework - our own framework :)

**Comment by mahendrapratap4022** [comment]
@cristianraiber I already create the PR with the same issue fix would be great if somebody merge after test it as lots of people have submitted the same issue.
