### ISSUE TITLE
Customizer mobile

### ISSUE THREAD

**Issue by razvanaldea89** [ColorlibHQ/philosophy#27]
When selecting responsive versions (  table or mobile  ) the icon doesn't stay active.
![customizer mobile bug](https://user-images.githubusercontent.com/44024114/56267436-7c4b2980-60f7-11e9-9a71-917d00d263f8.PNG)

**Comment by codepixar** [comment]
This is Epsilon Framework issue.

**Comment by codepixar** [comment]
Fixed
