### ISSUE TITLE
Maybe add a home icon in the customizer

### ISSUE THREAD

**Issue by razvanaldea89** [ColorlibHQ/philosophy#28]
A home customizer to return to the main panel. Other plugins might add new sections there
![philosofy home icon maybe](https://user-images.githubusercontent.com/44024114/56267553-cf24e100-60f7-11e9-9738-2019caaca920.PNG)

**Comment by codepixar** [comment]
This is Epsilon Framework issue.

**Comment by codepixar** [comment]
Fixed
