### ISSUE TITLE
Demo content import bug

### ISSUE THREAD

**Issue by razvanaldea89** [ColorlibHQ/philosophy#29]
When trying to import from "Demo content" section, if the last option isn't selected ( "Content" ) the import won't finalize ( it imports the selected option but won't tell the user that the import is over )

**Comment by codepixar** [comment]
I think it's Epsilon Framework issue.

**Comment by mahendrapratap4022** [comment]
@codepixar is right I have tested it too. The problem is in the package https://github.com/WPChill/epsilon-theme-dashboard.
