### ISSUE TITLE
About page built using static blocks?!

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/philosophy#3]
Epsilon Framework features repeater sections ... why use static fields for something like this?

**Comment by cristianraiber** [comment]
About panel in Customizer is completely broken now in: https://github.com/ColorlibHQ/philosophy/pull/10

**Comment by cristianraiber** [comment]
<img width="348" alt="image" src="https://user-images.githubusercontent.com/7841556/46077972-5ed66280-c19b-11e8-86be-e8de28ec8855.png">

**Comment by cristianraiber** [comment]
Your repeater implementation in: #10 is broken :) I have to save & refresh the Customizer for the changes to show in the previewer. Please fix this ASAP.

**Comment by cristianraiber** [comment]
@codepixar - this still hasn't been implemented.

**Comment by cristianraiber** [comment]
@codepixar - please show me a GIF or short video with this working :) At my end, after I add a new section, I have to hit save & reload for the changes to show up in the Previewer.

**Comment by codepixar** [comment]
Please check this https://www.hippovideo.io/video/play/r8uHib__OrFIqUYDqLiZnQ

**Comment by cristianraiber** [comment]
@codepixar - Weirdly, it doesn't work at my end. Going to close this for now.
