### ISSUE TITLE
Import wizard

### ISSUE THREAD

**Issue by razvanaldea89** [ColorlibHQ/philosophy#30]
If I don't select the last option for the import ( "contet" ) I can't go forward ( can't click next button )
![philosofy wizard bug](https://user-images.githubusercontent.com/44024114/56268290-a4d42300-60f9-11e9-96e1-33aea823c408.PNG)

**Comment by mahendrapratap4022** [comment]
Hi, I have tested this issue and it is in the epsilon-theme-dashboard package which we are using for the same. https://github.com/WPChill/epsilon-theme-dashboard.
