### ISSUE TITLE
Class 'Epsilon_Dashboard' not found

### ISSUE THREAD

**Issue by devansh393** [ColorlibHQ/philosophy#33]
I tried uploading the this theme to my wordpress account but below error came. Please help me resolve this issue. And if you can update when will the Philosophy wordpress theme will be launched officially, that would be great.

Fatal error: Uncaught Error: Class 'Epsilon_Dashboard' not found
in /home/u820306590/domains/devanshrastogi.com/public_html/wp-content/themes/philosophy/inc/class-epsilon-init-dashboard.php on line 179

Call stack:

Epsilon_init_Dashboard::init_dashboard()
wp-content/themes/philosophy/inc/class-epsilon-init-dashboard.php:67
Epsilon_init_Dashboard::__construct()
wp-content/themes/philosophy/inc/class-epsilon-init-dashboard.php:82
Epsilon_init_Dashboard::get_instance()
wp-content/themes/philosophy/inc/classes/Class-Config.php:46
Philosophy::init()
wp-content/themes/philosophy/inc/classes/Class-Config.php:32
Philosophy::__construct()
wp-content/themes/philosophy/functions.php:127
include()
wp-settings.php:508
require_once()
wp-config.php:79
require_once()
wp-load.php:37
require_once()
wp-admin/admin.php:34
require_once()
wp-admin/customize.php:13

**Comment by cristianraiber** [comment]
Do not clone github repo and you will not run into amy issues. Download provided theme zip from Colorlib site and that one works without a hitch.
