### ISSUE TITLE
Header color pallet not fully showing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/philosophy#35]
The color pallets for the header's following options do not fully appear :
Dropdown menu color: https://prnt.sc/uw1lc7
Dropdown menu hover color : https://prnt.sc/uw1liw

**Comment by mahendrapratap4022** [comment]
It's the epsilon-framework issue I have created the issue here https://github.com/WPChill/epsilon-framework/issues/197 and also created the PR with the fix https://github.com/WPChill/epsilon-framework/pull/198
