### ISSUE TITLE
The About Page will not appear in preview

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/philosophy#36]
If we try to change the about page, it will not appear in preview : 
https://drive.google.com/file/d/1LU9PN8qbGvsOwyj0fCSzOo4H0-LwlHSe/view

**Comment by mahendrapratap4022** [comment]
you have to select the about us template on the edit page first in order to use this option.

<img width="357" alt="Screenshot 2021-08-30 at 2 52 49 PM" src="https://user-images.githubusercontent.com/33213474/131317512-7cb8c61a-0608-4fd9-9d3b-e799946ab8f6.png">
