### ISSUE TITLE
Contact page will not appear in preview

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/philosophy#37]
The contact page will not appear in preview when we make changes on it : 
https://drive.google.com/file/d/1x6Neb2ZycUSzGPDyBP7H2raVoFJLRHAJ/view

**Comment by mahendrapratap4022** [comment]
It is working fine I have tested it, Make sure you select the contact page in the template like this.
<img width="357" alt="Screenshot 2021-08-30 at 2 47 06 PM" src="https://user-images.githubusercontent.com/33213474/131316739-6d12926a-7941-4c8b-9a97-86e3256f3238.png">
contact page template first
