### ISSUE TITLE
Footer page color pallet not fully showing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/philosophy#41]
If we to change the color on the following elements on the footer, we will not see the full color pallet :
Footer Widget Title Color : https://prnt.sc/uw2tc5
Footer Anchor Color : https://prnt.sc/uw2tso
Footer Anchor Hover Color: https://prnt.sc/uw2u1v

**Comment by mahendrapratap4022** [comment]
Hi, @Florin415 where exactly are you changing the color?  It would be great if you can share more details of it.

**Comment by mahendrapratap4022** [comment]
It's the epsilon-framework issue I have created the issue here https://github.com/WPChill/epsilon-framework/issues/197 and also created the PR with the fix https://github.com/WPChill/epsilon-framework/pull/198
