### ISSUE TITLE
🔥 🔥 🔥 Don't change prefix on Epsilon Framework

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/philosophy#9]
Why have you changed prefix on Epsilon framework to Philosophy? It makes no sense. 

Epsilon is a 3rd party framework and should be treated as such.

**Comment by cristianraiber** [comment]
This still isn't implemented in #10

**Comment by codepixar** [comment]
We have already solved Epsilon prefix issue in last PR ( 1.1.0 ).

http://prntscr.com/kyyd6y
http://prntscr.com/kyyghh

**Comment by codepixar** [comment]
Our developer checked he don't find other prefix in Epsilon Framework and Epsilon Dashboard. 
Screenshot:
http://prntscr.com/kyyp4q
Please could you provide us example screenshot.
